trigger: 
  branches:
    include:
    - dev
    - dev-mabar
    - test
    - master
  paths:
    include:
    - 'client/'

pr: none

variables:
  arcName: 'coronai'
  imageName: 'coronaiDocker'
  MOHarcName: 'IDFDocker'
  AzureContainerRegistry: 'AzureContainerRegistry'
  MOHContainerRegistry: 'MOHContainerRegistry'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  isMabarDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev-mabar')]

stages:
- stage:
  displayName: TestsAndBuildStage
  jobs:
  - job: BuildJob
    displayName: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.18'
      displayName: 'Install Node.js'

    # loading env variables for client dev without authentication
    - script: |
        echo "##vso[task.setvariable variable=REACT_APP_DB_API]$(DB_API_DEV_NO_AUTH)"
        echo "##vso[task.setvariable variable=REACT_APP_ENVIRONMENT]$(APP_ENVIRONMENT_DEV)"
        echo "##vso[task.setvariable variable=REACT_APP_GOOGLE_API_KEY]$(GOOGLE_API)"
        echo "##vso[task.setvariable variable=REACT_APP_INSTRUMENTATION_KEY]$(INSTRUMENTATION_KEY_DEV_NO_AUTH)"
        echo "##vso[task.setvariable variable=REACT_APP_SHOULD_POST_TO_AZURE]$(POST_TO_AZURE)"
      condition: eq(variables.isDev,true)
      displayName: 'setting .env for dev environment'

    # building dev client without authentication or any other environment
    - script: |
        cd client
        npm install
        npm run build
      displayName: 'npm build client'
      condition: eq(variables.isDev,true)

    # pushing dev client without authentication image
    - task: Docker@2
      condition: eq(variables.isDev,true)
      continueOnError: 'false'
      displayName: Push Dev client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client-dev

    # loading env variables to dev client with authentication
    - script: |
        echo "##vso[task.setvariable variable=REACT_APP_DB_API]$(DB_API_DEV)"
        echo "##vso[task.setvariable variable=REACT_APP_ENVIRONMENT]$(APP_ENVIRONMENT_DEV_AUTH)"
        echo "##vso[task.setvariable variable=REACT_APP_GOOGLE_API_KEY]$(GOOGLE_API)"
        echo "##vso[task.setvariable variable=REACT_APP_INSTRUMENTATION_KEY]$(INSTRUMENTATION_KEY_DEV_AUTH)"
        echo "##vso[task.setvariable variable=REACT_APP_SHOULD_POST_TO_AZURE]$(POST_TO_AZURE)"
      condition: eq(variables.isDev,true)
      displayName: 'setting .env for dev-auth environment'
    
    # building dev client with authentication
    - script: |
        cd client
        npm install
        npm run build
      condition: eq(variables.isDev,true)
      displayName: 'npm build client with auth'

    # pushing dev client with authentication image
    - task: Docker@2
      condition: eq(variables.isDev,true)
      continueOnError: 'false'
      displayName: Push Dev client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client-dev-auth

    # loading env variables for test client
    - script: |
        echo "##vso[task.setvariable variable=REACT_APP_DB_API]$(DB_API_TEST)"
        echo "##vso[task.setvariable variable=REACT_APP_ENVIRONMENT]$(APP_ENVIRONMENT_TEST)"
        echo "##vso[task.setvariable variable=REACT_APP_GOOGLE_API_KEY]$(GOOGLE_API)"
        echo "##vso[task.setvariable variable=REACT_APP_INSTRUMENTATION_KEY]$(INSTRUMENTATION_KEY_AUTOMATION_TEST)"
        echo "##vso[task.setvariable variable=REACT_APP_SHOULD_POST_TO_AZURE]$(POST_TO_AZURE)"
      condition: eq(variables.isTest,true)
      displayName: 'setting .env db route to test route'

    # building test client
    - script: |
        cd client
        npm install
        npm run build
      condition: eq(variables.isTest,true)
      displayName: 'npm build load testing client'

    # pushing test client to azure client registry
    - task: Docker@2
      condition: eq(variables.isTest,true)
      continueOnError: 'false'
      displayName: Push test client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client-test

    # pushing test client to MOH client registry
    - task: Docker@2
      condition: eq(variables.isTest,true)
      continueOnError: 'false'
      displayName: Push test client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(MOHarcName)'
        azureSubscriptionEndpoint: '$(MOHContainerRegistry)'
        containerRegistry: '$(MOHContainerRegistry)'
        tags: |
          client-test

    # loading env variables for prod client
    - script: |
        echo "##vso[task.setvariable variable=REACT_APP_DB_API]$(DB_API_PROD)"
        echo "##vso[task.setvariable variable=REACT_APP_ENVIRONMENT]$(APP_ENVIRONMENT_PROD)"
        echo "##vso[task.setvariable variable=REACT_APP_GOOGLE_API_KEY]$(GOOGLE_API)"
        echo "##vso[task.setvariable variable=REACT_APP_INSTRUMENTATION_KEY]$(INSTRUMENTATION_KEY_PROD)"
        echo "##vso[task.setvariable variable=REACT_APP_SHOULD_POST_TO_AZURE]$(POST_TO_AZURE)"
      condition: eq(variables.isMaster,true)
      displayName: 'setting .env db route to prod route'
    
    # building prod client
    - script: |
        cd client
        npm install
        npm run build
      displayName: 'npm build client'
      condition: eq(variables.isMaster,true)

    # pushing prod client to MOH client registry
    - task: Docker@2
      condition: eq(variables.isMaster,true)
      continueOnError: 'false'
      displayName: Push master client image to MOH container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(MOHarcName)'
        azureSubscriptionEndpoint: '$(MOHContainerRegistry)'
        containerRegistry: '$(MOHContainerRegistry)'
        tags: |
          client-master

  # Semantic release job (not working now)
  - job: 
    dependsOn: [BuildJob]
    displayName: SemanticRelease
    steps:  
    - task: NodeTool@0
      displayName: install NodeJs
      inputs:
        versionSpec: '10.19'

    - script: >
        npx -p semantic-release
        -p @semantic-release/git
        -p semantic-release-ado
        semantic-release
      env: { GH_TOKEN: $(GitHubToken) }
      displayName: 'Semantic release'
  
    - script: echo $(GH_TOKEN)
      displayName: 'Show next version'

# - stage: 
#   displayName: 'Deployment'
#     dependsOn: Build
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy job
#     pool:
#       vmImage: $(vmImageName)
#     environment: 'azooinmyluggagepipelinesjavascriptdocker.aksnamespace'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: DownloadPipelineArtifact@2
#             inputs:
#               artifactName: 'manifests'
#               downloadPath: '$(System.ArtifactsDirectory)/manifests'

#           - task: KubernetesManifest@0
#             displayName: Create imagePullSecret
#             inputs:
#               action: createSecret
#               secretName: $(imagePullSecret)
#               namespace: $(k8sNamespace)
#               dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
            
#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: deploy
#               namespace: $(k8sNamespace)
#               manifests: |
#                 $(System.ArtifactsDirectory)/manifests/deployment.yml
#                 $(System.ArtifactsDirectory)/manifests/service.yml
#               imagePullSecrets: |
#                 $(imagePullSecret)
#               containers: |
#                 $(containerRegistry)/$(imageRepository):$(tag)/
