trigger: 
  branches:
    include:
    - shiranTestingCi
  paths:
    include:
    - 'client/'

variables:
  arcName: 'coronai'
  imageName: 'coronaiDocker'
  MOHarcName: 'IDFDocker'
  AzureContainerRegistry: 'AzureContainerRegistry'
  MOHContainerRegistry: 'MOHContainerRegistry'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/Master')]
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/Test')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/Dev')]

stages:
- stage:
  displayName: TestsAndBuildStage
  jobs:
  - job:
    condition: eq(variables.isMaster,true)
    displayName: testingCondition
    steps:
    - script: |
        echo hi
      displayName: 'echo hi'

  - job:
    displayName: TestsAndBuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.18'
      displayName: 'Install Node.js'

    - script: |
        cd client
        npm install
        npm run build
      displayName: 'npm build client'
  
  - job:
    dependsOn: [ TestsAndBuildJob]
    displayName: buildAndPush dev branch client docker
    condition: eq(variables.isDev,true)
    steps:
    - task: Docker@2
      displayName: Build and push client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client-dev

  - job:
    dependsOn: [ TestsAndBuildJob]
    displayName: buildAndPush test branch client docker
    condition: eq(variables.isTest,true)
    steps:
    - task: Docker@2
      displayName: Build and push client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client-test

  - job:
    dependsOn: [ TestsAndBuildJob]
    displayName: buildAndPush master branch client docker
    condition: eq(variables.isMaster,true)
    steps:
    - task: Docker@2
      displayName: Build and push client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client-master

    - script: >
        npx -p semantic-release
        -p @semantic-release/git
        -p semantic-release-ado
        semantic-release
      env: { GH_TOKEN: $(GitHubToken) }
      displayName: 'Semantic release'
  
    - script: echo $(GH_TOKEN)
      displayName: 'Show next version'

# - stage: 
#   displayName: 'Deployment'
#     dependsOn: Build
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy job
#     pool:
#       vmImage: $(vmImageName)
#     environment: 'azooinmyluggagepipelinesjavascriptdocker.aksnamespace'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: DownloadPipelineArtifact@2
#             inputs:
#               artifactName: 'manifests'
#               downloadPath: '$(System.ArtifactsDirectory)/manifests'

#           - task: KubernetesManifest@0
#             displayName: Create imagePullSecret
#             inputs:
#               action: createSecret
#               secretName: $(imagePullSecret)
#               namespace: $(k8sNamespace)
#               dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
            
#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: deploy
#               namespace: $(k8sNamespace)
#               manifests: |
#                 $(System.ArtifactsDirectory)/manifests/deployment.yml
#                 $(System.ArtifactsDirectory)/manifests/service.yml
#               imagePullSecrets: |
#                 $(imagePullSecret)
#               containers: |
#                 $(containerRegistry)/$(imageRepository):$(tag)