trigger: 
  branches:
    include:
    - shiranTestingCi
  paths:
    include:
    - 'client/'

variables:
  azureSC: 'coronai'
  buildConfiguration: 'Release'
  location: 'North Europe'
  acrHostName: 'coronai.azurecr.io'
  arcName: 'coronai'
  rgName: 'spectrumFactory'
  imageName: 'coronaiDocker'
  webAppName: 'coronai'
  MOHarcName: 'IDFDocker'
  AzureContainerRegistry: 'AzureContainerRegistry'
  MOHContainerRegistry: 'MOHContainerRegistry'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

stages:
- stage:
  displayName: TestsAndBuildStage
  jobs:
  - job:
    condition: eq(variables.isMain,true)
    displayName: testingCondition
    steps:
    - script: |
        echo hi
      displayName: 'echo hi'

  - job:
    displayName: TestsAndBuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.18'
      displayName: 'Install Node.js'

    # - script: >
    #     npx -p semantic-release
    #     -p @semantic-release/git
    #     -p semantic-release-ado
    #     semantic-release
    #   env: { GH_TOKEN: $(GitHubToken) }
    #   displayName: 'Semantic release'

    # - script: echo $(GH_TOKEN)
    #   displayName: 'Show next version'

    - script: |
        cd client
        npm install
        npm run build
      displayName: 'npm build client'

    # - task: Docker@1
    #   displayName: Build an image to container registry
    #   inputs:
    #     repository: '$(arcName)'
    #     azureSubscriptionEndpoint: 'AzureSC'
    #     azureContainerRegistry: '$(acrHostName)'
    #     imageName: '$(imageName):(Build.BuildId)'
    #     useDefaultContext: false
    #     buildContext: '$(System.DefaultWorkingDirectory)'

    # - task: Docker@1
    #   displayName: push an image to container registry
    #   inputs:
    #     command: 'Push an image'
    #     azureSubscriptionEndpoint: 'AzureSC'
    #     azureContainerRegistry: '$(acrHostName)'
    #     imageName: '$(imageName):(Build.BuildId)'

    - task: Docker@2
      displayName: Build and push client image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/client/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          client

# - stage: 
#   displayName: 'Deployment'
#     dependsOn: Build
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy job
#     pool:
#       vmImage: $(vmImageName)
#     environment: 'azooinmyluggagepipelinesjavascriptdocker.aksnamespace'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: DownloadPipelineArtifact@2
#             inputs:
#               artifactName: 'manifests'
#               downloadPath: '$(System.ArtifactsDirectory)/manifests'

#           - task: KubernetesManifest@0
#             displayName: Create imagePullSecret
#             inputs:
#               action: createSecret
#               secretName: $(imagePullSecret)
#               namespace: $(k8sNamespace)
#               dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
            
#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: deploy
#               namespace: $(k8sNamespace)
#               manifests: |
#                 $(System.ArtifactsDirectory)/manifests/deployment.yml
#                 $(System.ArtifactsDirectory)/manifests/service.yml
#               imagePullSecrets: |
#                 $(imagePullSecret)
#               containers: |
#                 $(containerRegistry)/$(imageRepository):$(tag)