trigger:
- shiranTestingCi
variables:
    dockerName: "manivShtok"
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      cd client 
      npm install
      npm run build
    displayName: 'npm build client'

  - script: |
      cd server && npm install
    displayName: 'npm install server'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'client/'
      Contents: 'build/**' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    inputs:
      Contents: 'server/**' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
      displayName: 'Publish artifacts: drop'