-- Creating table chat_status

CREATE TABLE IF NOT EXISTS public.chat_status
(
    id integer NOT NULL,
    display_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT chat_status_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

-- Inserting data into table chat_status

INSERT INTO public.chat_status(id, display_name)
	VALUES (0,'ממתינה לשליחה')
	ON CONFLICT DO NOTHING;

INSERT INTO public.chat_status(id, display_name)
	VALUES (1,'אין ווטצאפ')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.chat_status(id, display_name)
	VALUES (2, 'נשלחה / בשיחה')
	ON CONFLICT DO NOTHING;

INSERT INTO public.chat_status(id, display_name)
	VALUES (3,'אין שיתוף פעולה')
	ON CONFLICT DO NOTHING;


INSERT INTO public.chat_status(id, display_name)
	VALUES (5,'ננטשה')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.chat_status(id, display_name)
	VALUES (6,'הושלמה')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.chat_status(id, display_name)
	VALUES (7,'בקשה לחקירה אנושית')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.chat_status(id, display_name)
	VALUES (8,'פרטי שיחה שגויים')
	ON CONFLICT DO NOTHING;

INSERT INTO public.chat_status(id, display_name)
	VALUES (11,'ממתינה לחיווי מבוט')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.chat_status(id, display_name)
	VALUES (99,'לא רלוונטי')
	ON CONFLICT DO NOTHING;
	
-- Creating table investigation_chat_status

CREATE TABLE IF NOT EXISTS public.investigation_chat_status
(
    id integer NOT NULL,
    display_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT investigation_chat_status_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

-- Inserting data into table investigation_chat_status

INSERT INTO public.investigation_chat_status(id, display_name)
	VALUES (1, 'חדשה')
	ON CONFLICT DO NOTHING;
INSERT INTO public.investigation_chat_status(id, display_name)
	VALUES (2, 'בטיפול')
	ON CONFLICT DO NOTHING;
INSERT INTO public.investigation_chat_status(id, display_name)
	VALUES (3, 'תקינה')
	ON CONFLICT DO NOTHING;
INSERT INTO public.investigation_chat_status(id, display_name)
	VALUES (4, 'הושלמה')
	ON CONFLICT DO NOTHING;
INSERT INTO public.investigation_chat_status(id, display_name)
	VALUES (99, 'לא רלוונטי')
	ON CONFLICT DO NOTHING;
	
-- Creating table investigator_reference_status

CREATE TABLE IF NOT EXISTS public.investigator_reference_status
(
    id integer NOT NULL,
    display_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT investigator_reference_status_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

-- Inserting data into table investigator_reference_status

INSERT INTO public.investigator_reference_status(id, display_name)
	VALUES (1, 'ממתין')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.investigator_reference_status(id, display_name)
	VALUES (2, 'בטיפול')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.investigator_reference_status(id, display_name)
	VALUES (3, 'הושלם')
	ON CONFLICT DO NOTHING;
	
INSERT INTO public.investigator_reference_status(id, display_name)
	VALUES (9, 'לא רלוונטי')
	ON CONFLICT DO NOTHING;
	
-- Creating table investigator_reference_reason

CREATE TABLE IF NOT EXISTS public.investigator_reference_reason
(
    id integer NOT NULL,
    display_name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT investigator_reference_reason_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

-- Inserting data into table investigator_reference_reason

INSERT INTO public.investigator_reference_reason(id, display_name)
	VALUES (1, 'בקשה לחקירה אנושית')
	ON CONFLICT DO NOTHING;

INSERT INTO public.investigator_reference_reason(id, display_name)
	VALUES (2, 'נמצא עם אוכלוסיה בסיכון')
	ON CONFLICT DO NOTHING;

INSERT INTO public.investigator_reference_reason(id, display_name)
	VALUES (3, 'בעייתי לקיום בידוד')
	ON CONFLICT DO NOTHING;
	
	

CREATE TABLE IF NOT EXISTS public.bot_investigation
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    epidemiology_number integer NOT NULL,
    chat_status_id integer,
    investigation_chat_status_id integer,
    read_from_bot_date timestamp without time zone,
    last_chat_date timestamp without time zone,
    investigator_reference_status_id integer,
    investigatior_reference_required boolean,
    investigation_chat_id character varying COLLATE pg_catalog."default",
    investigation_chat_start_date timestamp without time zone,
    CONSTRAINT bot_investigation_pkey PRIMARY KEY (id),
    CONSTRAINT epidemiology_number_unique UNIQUE (epidemiology_number),
    CONSTRAINT bot_investigation_chat_status_fkey FOREIGN KEY (chat_status_id)
        REFERENCES public.chat_status (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bot_investigation_investigation_chat_status_fkey FOREIGN KEY (investigation_chat_status_id)
        REFERENCES public.investigation_chat_status (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bot_investigation_investigation_fkey FOREIGN KEY (epidemiology_number)
        REFERENCES public.investigation (epidemiology_number) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT bot_investigation_investigator_reference_status_fkey FOREIGN KEY (Investigator_reference_status_id)
        REFERENCES public.investigator_reference_status (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;


-- Creating table bot_investigation_reference_reason


CREATE TABLE IF NOT EXISTS public.bot_investigation_reference_reason
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    bot_investigation_id integer NOT NULL,
    investigator_reference_reason_id integer NOT NULL,
    CONSTRAINT bot_investigation_reference_reason_pkey PRIMARY KEY (id),
    CONSTRAINT bot_invetigation_id_fkey FOREIGN KEY (bot_investigation_id)
        REFERENCES public.bot_investigation (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT investigator_reference_status_fkey FOREIGN KEY (investigator_reference_reason_id)
        REFERENCES public.investigator_reference_reason (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;