trigger: 
  branches:
    include:
    - shiranTestingCi
  paths:
    include:
    - 'server/'

variables:
  arcName: 'coronai'
  imageName: 'coronaiDocker'
  MOHarcName: 'IDFDocker'
  AzureContainerRegistry: 'AzureContainerRegistry'
  MOHContainerRegistry: 'MOHContainerRegistry'
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/Master')]
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/Test')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/Dev')]

stages:
- stage:
  displayName: TestsAndBuildStage
  jobs:
  - job: BuildJob
    displayName: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.18'
      displayName: 'Install Node.js'
  
  - job: buildDevServerDocker
    dependsOn: BuildJob
    displayName: buildAndPush dev branch server docker
    continueOnError: 'false'
    condition: eq(variables.isDev,true)
    steps:
    - task: Docker@2
      displayName: Build and push server image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/server/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          server-dev

  - job: buildTestServerDocker
    dependsOn: BuildJob
    displayName: buildAndPush test branch server docker
    continueOnError: 'false'
    condition: eq(variables.isTest,true)
    steps:
    - task: Docker@2
      displayName: Build and push server image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/server/Dockerfile'
        repository: '$(arcName)'
        azureSubscriptionEndpoint: '$(AzureContainerRegistry)'
        containerRegistry: '$(AzureContainerRegistry)'
        tags: |
          server-test

  - job: buildMasterServerDocker
    dependsOn: BuildJob
    displayName: buildAndPush master branch server docker
    continueOnError: 'false'
    condition: eq(variables.isMaster,true)
    steps:  
    - task: Docker@2
      displayName: Build and push server image to container registry
      inputs:
        command: buildAndPush
        dockerfile: '**/server/Dockerfile'
        repository: '$(MOHarcName)'
        azureSubscriptionEndpoint: '$(MOHContainerRegistry)'
        containerRegistry: '$(MOHContainerRegistry)'
        tags: |
          server-master
  
  - job: 
    dependsOn: [buildDevServerDocker, buildMasterServerDocker, buildTestServerDocker]
    displayName: SemanticRelease
    steps:
    - script: >
        npx -p semantic-release
        -p @semantic-release/git
        -p semantic-release-ado
        semantic-release
      env: { GH_TOKEN: $(GitHubToken) }
      displayName: 'Semantic release'

    - script: echo $(GH_TOKEN)
      displayName: 'Show next version'

# - stage: 
#   displayName: 'Deployment'
#     dependsOn: Build
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy job
#     pool:
#       vmImage: $(vmImageName)
#     environment: 'azooinmyluggagepipelinesjavascriptdocker.aksnamespace'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: DownloadPipelineArtifact@2
#             inputs:
#               artifactName: 'manifests'
#               downloadPath: '$(System.ArtifactsDirectory)/manifests'

#           - task: KubernetesManifest@0
#             displayName: Create imagePullSecret
#             inputs:
#               action: createSecret
#               secretName: $(imagePullSecret)
#               namespace: $(k8sNamespace)
#               dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
            
#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: deploy
#               namespace: $(k8sNamespace)
#               manifests: |
#                 $(System.ArtifactsDirectory)/manifests/deployment.yml
#                 $(System.ArtifactsDirectory)/manifests/service.yml
#               imagePullSecrets: |
#                 $(imagePullSecret)
#               containers: |
#                 $(containerRegistry)/$(imageRepository):$(tag)