import CovidPatient from './CovidPatient';

interface Exposure {
    id?: number,
    investigationId: number,
    exposureSource: CovidPatient | null,
    exposureDate?: Date,
    exposureAddress?: string,
    exposurePlaceSubType?: number,
    exposurePlaceType?: string,
    flightDestinationCity?: string,
    flightDestinationAirport?: string,
    flightOriginCity?: string,
    flightOriginAirport?: string,
    flightStartDate?: Date,
    flightEndDate?: Date,
    airline?: { id: number, displayName: string },
    flightNum?: string,
    flightOriginCountry?: string,
    flightDestinationCountry?: string,
    wasAbroad?: boolean,
    wasConfirmedExposure: boolean,
    isExposurePersonKnown: boolean | undefined,
    borderCheckpoint?: any,
    borderCheckpointType?: number,
    arrivalDateToIsrael?: Date,
    arrivalTimeToIsrael?: string,
    flightSeatNum?: string,
    otherFlightNum?: string,
    lastDestinationCountry?: string,
    borderCheckpointByBorderCheckpoint?: any,
    otherAirline?: string,
};

export default Exposure;
