import Contact from 'models/Contact';
import Address from 'models/Address';
import { DBAddress } from 'models/DBAddress';

interface InteractionEventDialogData {
    id?: number;
    placeType: string;
    startTime: Date;
    endTime: Date;
    unknownTime: boolean;
    externalizationApproval: boolean | null;
    investigationId: number;
    placeName?: string;
    placeDescription?: string;
    locationAddress: Address;
    placeSubType: number | null;
    busLine?: string;
    airline?: string;
    flightNum?: string;
    busCompany?: string;
    grade?: string;
    boardingStation?: string;
    cityOrigin?: string;
    endStation?: string;
    cityDestination?: string;
    contactPersonFirstName?: string;
    contactPersonLastName?: string;
    contactPersonPhoneNumber?: string;
    hospitalDepartment?: string;
    contacts: Contact[];
    flightDestinationAirport?: string;
    flightDestinationCity?: string;
    flightDestinationCountry?: string;
    flightOriginAirport?: string;
    flightOriginCity?: string;
    flightOriginCountry?: string;
    creationTime: Date;
    privateHouseAddress?: DBAddress;
};

export default InteractionEventDialogData;
