enum ChatStatusCode {
    WAITING_FOR_SENDING = 0,
    NO_WHATSAPP = 1,
    SENT = 2,
    NO_COOPERATION = 3,
    ABANDONED = 5,
    COMPLETED = 7,
    DUPLICATE_SESSION = 8,
    HUMAN_INVESTIGATION_REQUEST = 10,
    WRONG_CHAT_DETAILS = 9,
    WAITING_FOR_BOT_RESPONSE = 11,
    HUMAN_INVESTIGATION_STARTED = 12,
    COMPLETED_WITHOUT_CONTACTS = 13,
    HUMAN_INVESTIGATION_REQUIRED = 14,
    HUMAN_INVESTIGATION_PREFERNCE = 15,
    IRRELEVANT = 99
}

export default ChatStatusCode;
