enum InvestigationsFilterByFields {
    STATUS = 'STATUS',
    DESK_ID = 'DESK_ID',
    SEARCH_BAR = 'SEARCH_BAR',
    UNASSIGNED_USER = 'UNASSIGNED_USER',
    INACTIVE_USER = 'INACTIVE_USER',
    UNALLOCATED_USER = 'UNALLOCATED_USER',
    TIME_RANGE = 'TIME_RANGE',
    SUB_STATUS = 'SUB_STATUS',
    UNUSUAL_IN_PROGRESS = 'UNUSUAL_IN_PROGRESS',
    UNUSUAL_COMPLETED_NO_CONTACT = 'UNUSUAL_COMPLETED_NO_CONTACT',
    UNALLOCATED_DESK = 'UNALLOCATED_DESK',
    CHAT_STATUS = 'CHAT_STATUS',
    INVESTIGATOR_REFERENCE_STATUS = 'INVESTIGATOR_REFERENCE_STATUS',
    INCOMPLETED_BOT_INVESTIGATION = 'INCOMPLETED_BOT_INVESTIGATION',
    COMPLEXITY = 'COMPLEXITY',
    COMPLEXITY_REASON = 'COMPLEXITY_REASON',
    INVESTIGATIONS_WERENT_SENT_TO_BOT = 'INVESTIGATIONS_WERENT_SENT_TO_BOT',
    AGE='AGE',
};

export default InvestigationsFilterByFields;
