export const tableFilterTitle = {
    'STATUS': 'סטטוס',
    'DESK_ID': 'דסק',
    'SEARCH_BAR': '',
    'UNASSIGNED_USER': 'לא משוייכות לחוקר',
    'INACTIVE_USER': 'משוייכות לחוקרים לא פעילים',
    'UNALLOCATED_USER': 'לא משוייכות לחוקר',
    'TIME_RANGE': 'תאריך הגעת חקירה',
    'SUB_STATUS': 'תת סטטוס',
    'UNUSUAL_IN_PROGRESS': '',
    'UNUSUAL_COMPLETED_NO_CONTACT': '',
    'UNALLOCATED_DESK': 'לא משוייכות לדסק',
    'CHAT_STATUS': 'סטטוס שיחה בוט',
    'INVESTIGATOR_REFERENCE_STATUS': 'סטטוס התייחסות חוקר',
    'INCOMPLETED_BOT_INVESTIGATION': 'חקירות שלא הושלמו ע"י בוט',
    'COMPLEXITY': 'חקירות מורכבות',
    'COMPLEXITY_REASON': 'סיבה למורכבות חקירה',
    'INVESTIGATIONS_WERENT_SENT_TO_BOT': 'חקירות שלא נשלחו לבוט',
    'AGE': 'גיל',
}

