enum InteractionEventDialogFields {
    LOCATION_TYPE = 'locationType',
    START_TIME = 'startTime',
    END_TIME = 'endTime',
    EXTERNALIZATION_APPROVAL = 'externalizationApproval',
    INVESTIGATION_ID = 'investigationId',
    LOCATION_NAME = 'locationName',
    LOCATION_ADDRESS = 'locationAddress',
    TRAIN_LINE = 'trainLine',
    BUS_LINE = 'busLine',
    AIR_LINE = 'airLine',
    FLIGHT_NUMBER = 'flightNumber',
    BUS_COMPANY = 'busCompany',
    GRADE = 'grade',
    BOARDING_STATION = 'boardingStation',
    BOARDING_COUNTRY = 'boardingCountry',
    BOARDING_CITY = 'boardingCity',
    END_STATION = 'endStation',
    END_COUNTRY = 'endCountry',
    END_CITY = 'endCity',
    BUSINESS_CONTACT_NAME = 'businessContactName',
    BUSINESS_CONTACT_NUMBER = 'businessContactNumber',
    HOSPITAL_DEPARTMENT = 'hospitalDepartment',
}

export default InteractionEventDialogFields;